# python write_strokes.py > _strokes.py

# purpose: To produce configs from database to python use
# see _strokes.py

from _sqlite import conn

curr = conn.cursor()

sql = "select stroke_name name, stroke_svg svg from tw_strokes order by stroke_name;"
rs = curr.execute(sql, ())

print("# File auto-generated by write_strokes.py)")
print()
print("class strokes:")
for row in rs:
    print("    {0} = \"{1}\"".format(row['name'], row['svg']))
