# python write_glyphs.py > _glyphs.py

# purpose: To produce configs from database to python use
# see _strokes.py

from _sqlite import conn

curr = conn.cursor()

sql = """
select
    position_hex hexa,
    name,
    appearance,
    variable,
    `group`
from ucd_variables
where `group`!='' and variable!=''
order by `group`, position_hex;
"""

rs = curr.execute(sql, ())

print("# File auto-generated by write_glyphs.py")
print()
print("from _letters import letters")
print("l = letters()")
print()
print("glyphs = {")
for row in rs:
    print("    \"{0}\": (\"{1}\", \"{2}\", l.{3},),".format(row['variable'], row['hexa'], row["group"], row["variable"]))
print("}")
